Enhance: Dockerized inventory-manager
ColuLocalNetwork/fuse-inventory-manager pull request #40
Opened 2018-12-13 11:12 UTC by xiaods

- [ ] use docker-compose.overide.yml to override all variables which are in the config files by using ENV variables.

- [ ] I also want to be able to tell the docker do I need to run npm run dev or npm run qa or any other npm scripts command.

## Proposed changes

Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request.

If it fixes a bug or resolves a feature request, be sure to link to that issue.

## Types of changes

What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ ] I have read the [CONTRIBUTING](https://github.com/ColuLocalNetwork/inventory-manager/blob/master/.github/CONTRIBUTING.md) doc
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

2018-12-16 11:57 UTC, LiorRabin requested changes
Hello @xiaods, a few changes please:
1. We don't need to use the `.env` file as we already have static configuration files under `/config` folder. All non-static configuration like mongo for example can be a part of the `docker-compose.yml` in the `environment` section.
2. remove `docker-compose.prod.yml` and `docker-compose.test.yml` and add a `docker-compose-inventory-only.yml` or something similar.
3. Why the `OSSEUS_ENV` variable name and not just `ENV` ?
4. Why added `process.env.XXX` on the local configuration files?

2018-12-17 01:17 UTC, xiaods commented
@LiorRabin  i have update codebase for your review. please have a look again. thanks .

2018-12-17 08:18 UTC, LiorRabin requested changes
@xiaods thanks for the update, I still see you're using `.env` file - is there a way to remove it entirely? even in the `docker-compose.yml` and just use the `environment` property of the yml file?

2018-12-17 13:19 UTC, xiaods commented
@LiorRabin yes, remove .env file entirely and update README clearly. please check again.

2018-12-17 14:48 UTC, LiorRabin commented on README.md
> +Test, QA, Production with appropriate npm command: `cp docker-compose-inventory-only.yml docker-compose.override.yml && docker-compose up -d`
@xiaods why do we need to copy the yml file to `*.override.yml` file?

2018-12-18 07:55 UTC, LiorRabin approved these changes

2018-12-18 07:55 UTC, merged